name: Tests

on:
  push:
    branches:
      - '**'
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'

jobs:
  shellcheck_scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./scripts/shellcheck.sh

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: go test ./...

  sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd samples/basic && go build
